$hostsPath = "C:\Windows\System32\drivers\etc\hosts"
$blockedSites = @(
    "www.facebook.com",
    "facebook.com",
    "www.youtube.com",
    "youtube.com",
    # Add the main domains for torrent sites you want to block
    "www.thepiratebay.org",
    "thepiratebay.org",
    "www.1337x.to",
    "1337x.to",
    "www.yts.mx",
    "yts.mx",
    "www.eztv.re",
    "eztv.re",
    "www.limetorrents.info",
    "limetorrents.info",
    "www.rarbg.to",
    "rarbg.to",
    "www.nyaa.si",
    "nyaa.si",
    "www.torrentz2.eu",
    "torrentz2.eu",
    "www.torrentgalaxy.to",
    "torrentgalaxy.to",
    "www.torrentdownloads.me",
    "torrentdownloads.me",
    "www.torrentfunk.com",
    "torrentfunk.com",
    "www.torrents.me",
    "torrents.me",
    "www.torrents.io",
    "torrents.io",
    "www.torrents.co",
    "torrents.co",
    "www.torrents.to",
    "torrents.to",
    "www.torrents2.eu",
    "torrents2.eu",
    "www.torrents2.me",
    "torrents2.me",
    "www.torrents2.cc",
    "torrents2.cc",
    "www.torrents2.is",
    "torrents2.is",
    "www.torrents2.in",
    "torrents2.in",
    "www.torrents2.com",
    "torrents2.com",
    "www.torrents2.net",
    "torrents2.net",
    "www.torrents2.org",
    "torrents2.org",
    "www.torrents2.biz",
    "torrents2.biz",
    "www.torrents2.info",
    "torrents2.info",
    "www.torrents2.us",
    "torrents2.us",
    "www.torrents2.uk",
    "torrents2.uk",
    "www.torrents2.ca",
    "torrents2.ca",
    "www.torrents2.de",
    "torrents2.de",
    "www.torrents2.ru",
    "torrents2.ru",
    "www.torrents2.au",
    "torrents2.au",
    "www.torrents2.jp",
    "torrents2.jp",
    "www.torrents2.cn",
    "torrents2.cn",
    "www.torrents2.hk",
    "torrents2.hk",
    # Add the main domains for adult sites you want to block
    "www.pornhub.com",
    "pornhub.com"
)

foreach ($site in $blockedSites) {
    $entry = "127.0.0.1 `t$site"
    Add-Content -Path $hostsPath -Value $entry
}
